# To read: http://docs.travis-ci.com/user/languages/android/
# Note that we might require `gradle/wrapper/gradle-wrapper.jar`, which
# is ignored in ~/.gitignore_global, so add it with `git add -f`

# New infrastructure
sudo: false

# Build Environment
build_environment: ubuntu1204

# Language 
language: android

# Android specific for Travis
android:
  components:
    - build-tools-19.1.0
    - android-19
    - sysimg-19
    - extra-android-support
    - extra-google-google_play_services
    - extra-google-m2repository
  licenses:
    - 'android-sdk-license-.+'
    - '.*intel.+'

# Cache dependencies for faster builds
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

# Version Numbers
jdk:
 - oraclejdk7

# Environment Variables
# https://github.com/travis-ci/travis-ci/issues/3695
env:
  global:
    MALLOC_ARENA_MAX=2

# Before Installation
before_install:
 - ./install-dummykeys.sh

# Installation
# - sudo apt-get install -u lib32stdc++6 lib32z1
install:
 - ./gradlew clean assemble

# Run before the script
#before_script:

# Jobs to test on the script
script:
 - ./gradlew check

# Notifications
notifications:
    email: false

# Run after the script
#after_script:
